# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\wei\weiProgramme\projects\graduation\qtTree\qttree.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_qttree(object):
    def setupUi(self, qttree):
        qttree.setObjectName(_fromUtf8("qttree"))
        qttree.resize(1002, 573)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(qttree.sizePolicy().hasHeightForWidth())
        qttree.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(qttree)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(9, 7, 991, 521))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wide Latin"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_3.addWidget(self.label_13)
        self.tableWidget_3 = QtGui.QTableWidget(self.horizontalLayoutWidget_5)
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.verticalLayout_3.addWidget(self.tableWidget_3)
        self.label_14 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wide Latin"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_3.addWidget(self.label_14)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_15 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_10.addWidget(self.label_15)
        self.lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_10.addWidget(self.lineEdit)
        self.toolButton_3 = QtGui.QToolButton(self.horizontalLayoutWidget_5)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.horizontalLayout_10.addWidget(self.toolButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_16 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_16.setFocusPolicy(QtCore.Qt.TabFocus)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_11.addWidget(self.label_16)
        self.comboBox_5 = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.horizontalLayout_11.addWidget(self.comboBox_5)
        self.horizontalLayout_11.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_17 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_12.addWidget(self.label_17)
        self.comboBox_6 = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.horizontalLayout_12.addWidget(self.comboBox_6)
        self.horizontalLayout_12.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.pushButton_3 = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_13.addWidget(self.pushButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.line_3 = QtGui.QFrame(self.horizontalLayoutWidget_5)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.label_18 = QtGui.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Wide Latin"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_3.addWidget(self.label_18)
        self.textBrowser_6 = QtGui.QTextBrowser(self.horizontalLayoutWidget_5)
        self.textBrowser_6.setObjectName(_fromUtf8("textBrowser_6"))
        self.verticalLayout_3.addWidget(self.textBrowser_6)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.graphicsView = QtGui.QGraphicsView(self.horizontalLayoutWidget_5)
        self.graphicsView.setEnabled(True)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView.setForegroundBrush(brush)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_4.addWidget(self.graphicsView)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.pushButton_6 = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_14.addWidget(self.pushButton_6)
        self.pushButton_4 = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_4.setText(_fromUtf8(""))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_14.addWidget(self.pushButton_4)
        self.pushButton_8 = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_8.setText(_fromUtf8(""))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_14.addWidget(self.pushButton_8)
        self.pushButton_7 = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_7.setText(_fromUtf8(""))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_14.addWidget(self.pushButton_7)
        self.commandLinkButton = QtGui.QCommandLinkButton(self.horizontalLayoutWidget_5)
        self.commandLinkButton.setObjectName(_fromUtf8("commandLinkButton"))
        self.horizontalLayout_14.addWidget(self.commandLinkButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 2)
        qttree.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(qttree)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        qttree.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(qttree)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1002, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menu = QtGui.QMenu(self.menuBar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menuBar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menuBar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        qttree.setMenuBar(self.menuBar)
        self.action = QtGui.QAction(qttree)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_2 = QtGui.QAction(qttree)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.action_3 = QtGui.QAction(qttree)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.action_Ctrl_S = QtGui.QAction(qttree)
        self.action_Ctrl_S.setObjectName(_fromUtf8("action_Ctrl_S"))
        self.action_4 = QtGui.QAction(qttree)
        self.action_4.setObjectName(_fromUtf8("action_4"))
        self.action_5 = QtGui.QAction(qttree)
        self.action_5.setObjectName(_fromUtf8("action_5"))
        self.action_6 = QtGui.QAction(qttree)
        self.action_6.setObjectName(_fromUtf8("action_6"))
        self.action_7 = QtGui.QAction(qttree)
        self.action_7.setObjectName(_fromUtf8("action_7"))
        self.menu.addAction(self.action_3)
        self.menu_2.addAction(self.action_6)
        self.menu_2.addAction(self.action_7)
        self.menu_3.addAction(self.action_4)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(qttree)
        QtCore.QMetaObject.connectSlotsByName(qttree)

    def retranslateUi(self, qttree):
        qttree.setWindowTitle(_translate("qttree", "Tree Health", None))
        self.label_13.setText(_translate("qttree", "树木信息--------------------------------------", None))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("qttree", "树木编号", None))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("qttree", "树木种类", None))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("qttree", "年龄", None))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("qttree", "产地", None))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("qttree", "保护等级", None))
        self.label_14.setText(_translate("qttree", "图片信息--------------------------------------", None))
        self.label_15.setText(_translate("qttree", "图片位置", None))
        self.toolButton_3.setText(_translate("qttree", "...", None))
        self.label_16.setText(_translate("qttree", "树木编号", None))
        self.label_17.setText(_translate("qttree", "诊断内容", None))
        self.pushButton_3.setText(_translate("qttree", "开始诊断", None))
        self.label_18.setText(_translate("qttree", "诊断结果--------------------------------------", None))
        self.pushButton_6.setText(_translate("qttree", "画笔", None))
        self.commandLinkButton.setText(_translate("qttree", "清除所有(Ctrl+l)", None))
        self.menu.setTitle(_translate("qttree", "文件", None))
        self.menu_2.setTitle(_translate("qttree", "操作", None))
        self.menu_3.setTitle(_translate("qttree", "帮助", None))
        self.action.setText(_translate("qttree", "设置", None))
        self.action_2.setText(_translate("qttree", "退出", None))
        self.action_3.setText(_translate("qttree", "退出", None))
        self.action_Ctrl_S.setText(_translate("qttree", "保存(Ctrl+S)", None))
        self.action_4.setText(_translate("qttree", "关于", None))
        self.action_5.setText(_translate("qttree", "测试", None))
        self.action_6.setText(_translate("qttree", "训练", None))
        self.action_7.setText(_translate("qttree", "诊断", None))

